In [14]:
import numpy as np
a=np.random.rand(4,4,2)
print(a)
a.shape

[[[ 0.19788631  0.27020174]
  [ 0.728404    0.74812492]
  [ 0.71815248  0.31910748]
  [ 0.61718034  0.37304493]]

 [[ 0.47769768  0.15297759]
  [ 0.52992065  0.66542139]
  [ 0.71022186  0.34808326]
  [ 0.32281773  0.07628203]]

 [[ 0.22928848  0.3408225 ]
  [ 0.84150996  0.57700549]
  [ 0.03514401  0.06344385]
  [ 0.00331075  0.20132943]]

 [[ 0.93553239  0.13487517]
  [ 0.13738428  0.22216185]
  [ 0.94240592  0.68756162]
  [ 0.02758003  0.78307553]]]


(4, 4, 2)

In [12]:
a_t=a.reshape(-1,1)  #multipy other dimensions except first
print(a_t)
a_t.shape

[[ 0.13877527]
 [ 0.25790695]
 [ 0.95107245]
 [ 0.8401785 ]
 [ 0.83290583]
 [ 0.35387864]
 [ 0.15065344]
 [ 0.5334584 ]
 [ 0.06874284]
 [ 0.66267103]
 [ 0.51408808]
 [ 0.66431472]
 [ 0.36433447]
 [ 0.74917963]
 [ 0.18669623]
 [ 0.5383251 ]
 [ 0.82651212]
 [ 0.94533241]
 [ 0.73706165]
 [ 0.72382194]
 [ 0.25827058]
 [ 0.98788   ]
 [ 0.73147137]
 [ 0.83545408]
 [ 0.34814176]
 [ 0.12440567]
 [ 0.59349378]
 [ 0.58281431]
 [ 0.66115573]
 [ 0.55727527]
 [ 0.02963794]
 [ 0.84938603]]


(32, 1)

In [15]:
a=np.array([[1.,2.,-1.],[3.,4.,-3.2]])
print(a)

[[ 1.   2.  -1. ]
 [ 3.   4.  -3.2]]


TypeError: 'CClass' object is not callable

In [4]:
print(a.T)

[[ 1.   3. ]
 [ 2.   4. ]
 [-1.  -3.2]]


In [5]:
a.reshape(3,1,1)

ValueError: cannot reshape array of size 6 into shape (3,1,1)

In [19]:
np.c_[np.array([1,2]),np.array([3,2]) ,np.array([4,5])]

array([[1, 3, 4],
       [2, 2, 5]])