# Vectorization

let us try the code on the coursera

In [8]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
import time
a=time.time()
print(a)

1505998926.3423946


use time function to test the time spending using vetcorization

In [11]:
a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()
print("vectotized version:"+ str(1000*(toc-tic))+"ms")
print(c)

c=0
tic=time.time()
for i in range(1000000):
    c+= a[i]*b[i]
toc=time.time()
print("non-vectotized version:"+ str(1000*(toc-tic))+"ms")
print(c)

vectotized version:0.9756088256835938ms
250080.142527
non-vectotized version:959.0935707092285ms
250080.142527


almost 1000 times larger comparison with non-vectorized and vectorized

In [17]:
u=np.zeros((3,2))
print(u)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [9]:
u=np.array([1,2,3,4])
v=np.maximum(u,0)
print(v)

[1 2 3 4]


In [11]:
print(u.T)
print(np.dot(u,v))
print(np.dot(u.T,v))

[1 2 3 4]
30
30


In [17]:
a=np.array([1,3,3,4])
print(a)
b=a>2
print(b)

[1 3 3 4]
[False  True  True  True]


In [21]:
import random
random.randint(1,100)

91

## 2.6.3 Broadcasting example

In [7]:
import numpy as np

A=np.array([[56.0,0.0,4.4,68.0],
            [1.2,104.0,52.0,8.0],
             [1.8,135.0,99.0,0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [12]:
cal=A.sum(axis=0)  #axis=0 means multiply vertically , axis=1 means multiply parallel
print(cal)

[  59.   239.   155.4   76.9]


In [15]:
percentage = 100*A/cal   #use cal.reshape(1,4) is the same
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [17]:
a=np.array([1,2,3])
b=a+a.reshape(3,1)
print(b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


## 2.6.4 python-numpy vectors

In [37]:
import numpy as np
#import random

a=np.random.rand(5)  #create gaussian random
print(a)

[ 0.60032602  0.11285429  0.22886282  0.81718017  0.33364307]


In [38]:
a.shape  #a and a.T look like the same

(5,)

the answer above is neither a column vector nor a row vector

In [39]:
c=a.reshape(5,1)
print(c)
b=c.T
print(b)

[[ 0.60032602]
 [ 0.11285429]
 [ 0.22886282]
 [ 0.81718017]
 [ 0.33364307]]
[[ 0.60032602  0.11285429  0.22886282  0.81718017  0.33364307]]


And we can use previous random.rand to create matrix or vectors

In [41]:
a=np.random.rand(5,1)
print(a)

[[ 0.14954972]
 [ 0.04079504]
 [ 0.38360901]
 [ 0.64635412]
 [ 0.44659183]]


In [43]:
print(np.dot(a.T,a))
print(np.dot(a,a.T))

[[ 0.78840314]]
[[ 0.02236512  0.00610089  0.05736862  0.09666208  0.06678768]
 [ 0.00610089  0.00166423  0.01564934  0.02636804  0.01821873]
 [ 0.05736862  0.01564934  0.14715588  0.24794727  0.17131665]
 [ 0.09666208  0.02636804  0.24794727  0.41777365  0.28865647]
 [ 0.06678768  0.01821873  0.17131665  0.28865647  0.19944426]]


In [45]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)
c=a*b
print(c)

[[ 1.28990568 -0.61590711  1.45509295]
 [-4.12014703  2.58674491  4.11292202]
 [ 1.29945502  0.24515477 -0.12019415]]


** normalization **
- first

In [62]:
import numpy as np
a=np.array([[1,1,1], [1,1,1]])
print(a)
np.linalg.norm(a,ord=3,axis=1,keepdims=True)

[[1 1 1]
 [1 1 1]]


array([[ 1.44224957],
       [ 1.44224957]])

<font color='blue'>
**What you need to remember:**
- np.exp(x) works for any np.array x and applies the exponential function to every coordinate
- the sigmoid function and its gradient
- image2vector is commonly used in deep learning
- np.reshape is widely used. In the future, you'll see that keeping your matrix/vector dimensions straight will go toward eliminating a lot of bugs. 
- numpy has efficient built-in functions
- broadcasting is extremely useful